// Static completion catalogs for T-SQL. Kept flat and inline (not fetched)
// so the completion provider has zero I/O on the hot path. Grouped by role
// so the provider can assign the right monaco CompletionItemKind + sort tier
// without extra bookkeeping.
//
// Casing convention: source strings here are uppercase so the inserted text
// matches the T-SQL house style used across the rest of the app (matches how
// ADS ships its own suggestions).

export interface StaticCompletion {
  label: string;
  detail: string;
  documentation?: string;
}

// Reserved words + statement openers. Multi-word entries (LEFT JOIN,
// IS NOT NULL) are intentional — Monaco filters them just fine when the user
// types the leading word.
export const TSQL_KEYWORDS: StaticCompletion[] = [
  { label: 'SELECT', detail: 'keyword' },
  { label: 'FROM', detail: 'keyword' },
  { label: 'WHERE', detail: 'keyword' },
  { label: 'JOIN', detail: 'keyword' },
  { label: 'LEFT JOIN', detail: 'keyword' },
  { label: 'INNER JOIN', detail: 'keyword' },
  { label: 'RIGHT JOIN', detail: 'keyword' },
  { label: 'FULL OUTER JOIN', detail: 'keyword' },
  { label: 'ON', detail: 'keyword' },
  { label: 'GROUP BY', detail: 'keyword' },
  { label: 'ORDER BY', detail: 'keyword' },
  { label: 'HAVING', detail: 'keyword' },
  { label: 'LIMIT', detail: 'keyword' },
  { label: 'TOP', detail: 'keyword' },
  { label: 'INTO', detail: 'keyword' },
  { label: 'INSERT', detail: 'keyword' },
  { label: 'UPDATE', detail: 'keyword' },
  { label: 'DELETE', detail: 'keyword' },
  { label: 'MERGE', detail: 'keyword' },
  { label: 'WITH', detail: 'keyword' },
  { label: 'AS', detail: 'keyword' },
  { label: 'DISTINCT', detail: 'keyword' },
  { label: 'UNION', detail: 'keyword' },
  { label: 'UNION ALL', detail: 'keyword' },
  { label: 'INTERSECT', detail: 'keyword' },
  { label: 'EXCEPT', detail: 'keyword' },
  { label: 'EXISTS', detail: 'keyword' },
  { label: 'IN', detail: 'keyword' },
  { label: 'BETWEEN', detail: 'keyword' },
  { label: 'LIKE', detail: 'keyword' },
  { label: 'IS NULL', detail: 'keyword' },
  { label: 'IS NOT NULL', detail: 'keyword' },
  { label: 'AND', detail: 'keyword' },
  { label: 'OR', detail: 'keyword' },
  { label: 'NOT', detail: 'keyword' },
  { label: 'CASE', detail: 'keyword' },
  { label: 'WHEN', detail: 'keyword' },
  { label: 'THEN', detail: 'keyword' },
  { label: 'ELSE', detail: 'keyword' },
  { label: 'END', detail: 'keyword' },
  { label: 'CAST', detail: 'keyword' },
  { label: 'TRY_CAST', detail: 'keyword' },
  { label: 'CONVERT', detail: 'keyword' },
  { label: 'TRY_CONVERT', detail: 'keyword' },
  { label: 'CREATE', detail: 'keyword' },
  { label: 'ALTER', detail: 'keyword' },
  { label: 'DROP', detail: 'keyword' },
  { label: 'TABLE', detail: 'keyword' },
  { label: 'VIEW', detail: 'keyword' },
  { label: 'INDEX', detail: 'keyword' },
  { label: 'PROCEDURE', detail: 'keyword' },
  { label: 'FUNCTION', detail: 'keyword' },
  { label: 'TRIGGER', detail: 'keyword' },
  { label: 'SCHEMA', detail: 'keyword' },
  { label: 'DATABASE', detail: 'keyword' },
  { label: 'PRIMARY KEY', detail: 'keyword' },
  { label: 'FOREIGN KEY', detail: 'keyword' },
  { label: 'REFERENCES', detail: 'keyword' },
  { label: 'CHECK', detail: 'keyword' },
  { label: 'DEFAULT', detail: 'keyword' },
  { label: 'IDENTITY', detail: 'keyword' },
  { label: 'NULL', detail: 'keyword' },
  { label: 'NOT NULL', detail: 'keyword' },
  { label: 'DECLARE', detail: 'keyword' },
  { label: 'SET', detail: 'keyword' },
  { label: 'EXEC', detail: 'keyword' },
  { label: 'EXECUTE', detail: 'keyword' },
  { label: 'BEGIN', detail: 'keyword' },
  { label: 'COMMIT', detail: 'keyword' },
  { label: 'ROLLBACK', detail: 'keyword' },
  { label: 'TRANSACTION', detail: 'keyword' },
  { label: 'TRY', detail: 'keyword' },
  { label: 'CATCH', detail: 'keyword' },
  { label: 'THROW', detail: 'keyword' },
  { label: 'RETURN', detail: 'keyword' },
  { label: 'IF', detail: 'keyword' },
  { label: 'ELSE IF', detail: 'keyword' },
  { label: 'WHILE', detail: 'keyword' },
  { label: 'BREAK', detail: 'keyword' },
  { label: 'CONTINUE', detail: 'keyword' },
  { label: 'PRINT', detail: 'keyword' },
  { label: 'GO', detail: 'batch separator' },
];

// Aggregate + scalar + window fns. `detail` distinguishes categories so the
// hover popup gives a useful hint without needing per-item docs.
export const TSQL_FUNCTIONS: StaticCompletion[] = [
  { label: 'COUNT', detail: 'aggregate' },
  { label: 'SUM', detail: 'aggregate' },
  { label: 'AVG', detail: 'aggregate' },
  { label: 'MIN', detail: 'aggregate' },
  { label: 'MAX', detail: 'aggregate' },
  { label: 'ROUND', detail: 'scalar function' },
  { label: 'ABS', detail: 'scalar function' },
  { label: 'CEILING', detail: 'scalar function' },
  { label: 'FLOOR', detail: 'scalar function' },
  { label: 'POWER', detail: 'scalar function' },
  { label: 'SQRT', detail: 'scalar function' },
  { label: 'PI', detail: 'scalar function' },
  { label: 'RAND', detail: 'scalar function' },
  { label: 'LEN', detail: 'string function' },
  { label: 'LOWER', detail: 'string function' },
  { label: 'UPPER', detail: 'string function' },
  { label: 'TRIM', detail: 'string function' },
  { label: 'LTRIM', detail: 'string function' },
  { label: 'RTRIM', detail: 'string function' },
  { label: 'SUBSTRING', detail: 'string function' },
  { label: 'LEFT', detail: 'string function' },
  { label: 'RIGHT', detail: 'string function' },
  { label: 'REPLACE', detail: 'string function' },
  { label: 'REPLICATE', detail: 'string function' },
  { label: 'REVERSE', detail: 'string function' },
  { label: 'STUFF', detail: 'string function' },
  { label: 'CHARINDEX', detail: 'string function' },
  { label: 'PATINDEX', detail: 'string function' },
  { label: 'CONCAT', detail: 'string function' },
  { label: 'CONCAT_WS', detail: 'string function' },
  { label: 'FORMAT', detail: 'string function' },
  { label: 'STR', detail: 'string function' },
  { label: 'GETDATE', detail: 'date function' },
  { label: 'GETUTCDATE', detail: 'date function' },
  { label: 'SYSDATETIME', detail: 'date function' },
  { label: 'DATEADD', detail: 'date function' },
  { label: 'DATEDIFF', detail: 'date function' },
  { label: 'DATEPART', detail: 'date function' },
  { label: 'DATENAME', detail: 'date function' },
  { label: 'YEAR', detail: 'date function' },
  { label: 'MONTH', detail: 'date function' },
  { label: 'DAY', detail: 'date function' },
  { label: 'EOMONTH', detail: 'date function' },
  { label: 'ISDATE', detail: 'scalar function' },
  { label: 'ISNUMERIC', detail: 'scalar function' },
  { label: 'ISNULL', detail: 'scalar function' },
  { label: 'COALESCE', detail: 'scalar function' },
  { label: 'NULLIF', detail: 'scalar function' },
  { label: 'IIF', detail: 'scalar function' },
  { label: 'CHOOSE', detail: 'scalar function' },
  { label: 'NEWID', detail: 'scalar function' },
  { label: 'NEWSEQUENTIALID', detail: 'scalar function' },
  { label: 'ROW_NUMBER', detail: 'window function' },
  { label: 'RANK', detail: 'window function' },
  { label: 'DENSE_RANK', detail: 'window function' },
  { label: 'NTILE', detail: 'window function' },
  { label: 'LAG', detail: 'window function' },
  { label: 'LEAD', detail: 'window function' },
  { label: 'FIRST_VALUE', detail: 'window function' },
  { label: 'LAST_VALUE', detail: 'window function' },
  { label: 'OVER', detail: 'window clause' },
  { label: 'PARTITION BY', detail: 'window clause' },
  { label: 'JSON_VALUE', detail: 'JSON function' },
  { label: 'JSON_QUERY', detail: 'JSON function' },
  { label: 'JSON_MODIFY', detail: 'JSON function' },
  { label: 'OPENJSON', detail: 'JSON function' },
  { label: 'TRY_PARSE', detail: 'scalar function' },
  { label: 'HASHBYTES', detail: 'crypto function' },
  { label: 'CHECKSUM', detail: 'scalar function' },
  { label: 'BINARY_CHECKSUM', detail: 'scalar function' },
];

// SQL Server data types. Show up in CREATE/ALTER TABLE and CAST contexts.
export const TSQL_TYPES: StaticCompletion[] = [
  { label: 'INT', detail: 'type' },
  { label: 'BIGINT', detail: 'type' },
  { label: 'SMALLINT', detail: 'type' },
  { label: 'TINYINT', detail: 'type' },
  { label: 'BIT', detail: 'type' },
  { label: 'DECIMAL', detail: 'type' },
  { label: 'NUMERIC', detail: 'type' },
  { label: 'MONEY', detail: 'type' },
  { label: 'SMALLMONEY', detail: 'type' },
  { label: 'FLOAT', detail: 'type' },
  { label: 'REAL', detail: 'type' },
  { label: 'DATE', detail: 'type' },
  { label: 'TIME', detail: 'type' },
  { label: 'DATETIME', detail: 'type' },
  { label: 'DATETIME2', detail: 'type' },
  { label: 'SMALLDATETIME', detail: 'type' },
  { label: 'DATETIMEOFFSET', detail: 'type' },
  { label: 'CHAR', detail: 'type' },
  { label: 'VARCHAR', detail: 'type' },
  { label: 'TEXT', detail: 'type' },
  { label: 'NCHAR', detail: 'type' },
  { label: 'NVARCHAR', detail: 'type' },
  { label: 'NTEXT', detail: 'type' },
  { label: 'BINARY', detail: 'type' },
  { label: 'VARBINARY', detail: 'type' },
  { label: 'IMAGE', detail: 'type' },
  { label: 'UNIQUEIDENTIFIER', detail: 'type' },
  { label: 'XML', detail: 'type' },
  { label: 'GEOGRAPHY', detail: 'type' },
  { label: 'GEOMETRY', detail: 'type' },
  { label: 'HIERARCHYID', detail: 'type' },
];
