//! Schema tree types for the object explorer.
//!
//! Shape mirrors the frontend `SchemaInfo`/`SchemaNode` types so the wire
//! contract stays a single struct swap, not a translation layer.

use serde::Serialize;
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct SchemaInfo {
    pub connection_id: Uuid,
    pub schemas: Vec<SchemaNode>,
}

#[derive(Debug, Clone, Serialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct SchemaNode {
    pub name: String,
    pub tables: Vec<TableInfo>,
    pub views: Vec<TableInfo>,
    pub procedures: Vec<RoutineInfo>,
    pub functions: Vec<RoutineInfo>,
}

#[derive(Debug, Clone, Serialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct TableInfo {
    pub schema: String,
    pub name: String,
    // Frontend renders `${schema}.${name}` as the tree key and shows rowCount
    // in the leaf. Columns come later via a per-table drill-in call.
    pub row_count: Option<u64>,
    pub column_count: Option<u32>,
}

#[derive(Debug, Clone, Serialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct RoutineInfo {
    pub schema: String,
    pub name: String,
}

// Per-table editability metadata. Frontend uses `is_editable` to gate the
// "Edit" button on the browse grid; a missing PK means we can't build a safe
// WHERE clause for UPDATE/DELETE, so we stay read-only.
#[derive(Debug, Clone, Serialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct TableMetadata {
    pub schema: String,
    pub name: String,
    pub is_editable: bool,
    pub primary_key: Vec<String>,
    pub columns: Vec<TableColumn>,
}

#[derive(Debug, Clone, Serialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct TableColumn {
    pub name: String,
    // Rendered form, e.g. "int", "nvarchar(50)", "decimal(18,4)". Built by
    // combining DATA_TYPE + length/precision/scale from INFORMATION_SCHEMA.
    pub sql_type: String,
    pub is_nullable: bool,
    // IDENTITY column, auto-generated by the server. INSERTs must skip it and
    // UPDATEs against it get rejected with SQL Server error 8102.
    pub is_identity: bool,
    // Computed columns are read-only, even if the base table has a PK.
    pub is_computed: bool,
    // rowversion / timestamp columns. Server maintains them on every write, so
    // any client-supplied value gets rejected the same way IDENTITY does.
    pub is_rowversion: bool,
    // Derived from the flags above so the frontend has a single truth for
    // whether to allow cell edits. Kept alongside the raw flags so callers can
    // still render a specific tooltip explaining the reason.
    pub is_editable: bool,
    pub default_expression: Option<String>,
    pub ordinal: u32,
}

// Result of a `execute_transaction` call. `committed = false` means we rolled
// back and `failed_statement_index` + `error_message` carry the partial info;
// the frontend needs both to highlight the failing pending edit.
#[derive(Debug, Clone, Serialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct TransactionResult {
    pub committed: bool,
    pub rows_affected: u64,
    pub statement_count: u32,
    pub duration_ms: u32,
    pub failed_statement_index: Option<u32>,
    pub error_message: Option<String>,
}
